### ISSUE TITLE
Base wrong format error.

### ISSUE THREAD

**Issue by LatusPL** [rnielikki/CustomMusicCreator#1]
Im trying to make a custom theme but when i try doing it, Everything works fine just base has error with format. The format is literally wave which is accepted and idk what to do. After testing music with the test music feature, everything was just fine and played like normal. here is the error:

[ SPLITTER ] Started to Split --- Base.wav
Base.wav successfully splitted.
[ SPLITTER ] Started to Split --- Level01.wav
Level01.wav successfully splitted.
[ SPLITTER ] Started to Split --- Level02.wav
Level02.wav successfully splitted.
[ SPLITTER ] Started to Split --- Level03.wav
Level03.wav successfully splitted.
[ ATRAC CONVERTER ] Started to convert to Atrac--- Base.wav
SCEI ATRAC3plus Codec TOOL Version 2.0.0.0
SCE CONFIDENTIAL 
Copyright(C) 2007 Sony Computer Entertainment Inc. All Rights Reserved.
	*** built w/ ATRAC3plus library version 1.02 ***
Usage : at3tool [-<option>] file1 file2
  -e : encode file1(16bit linear PCM wav file) to file2 
below options only affects to encoding mode(when not, they will be ignored)
  -br N: specify the bitrate Nkbps
  -loop S E: specify the loop start point is S samples from the beginning
             specify the loop end   point is E samples from the beginning
             S and E must satisfy under conditon
             0 <= S < S + 6143 <= E < number of samples in file1
  -wholeloop: set the whole loop
  -d : decode to file1 to file2(16bit linear PCM wav file)
below options only affects to decoding mode(when not, they will be ignored)
  -repeat N: repeating LOOP part N times(default 2)
[PSP_AT3TOOL] Failed to create file from base-1.wav. An empty file was created as result. Did you check format?

**Comment by kanelikki** [comment]
![image](https://user-images.githubusercontent.com/5599742/215287250-b02e1229-1c47-4ceb-82c1-088b10b1f9dc.png)
have you tried set encoding to "Signed 16-bit PCM"?
I found other encoding doesn't work, and shows this message

**Comment by LatusPL** [comment]
oh... ok i will try.

**Comment by kanelikki** [comment]
issue solved, improved message in [this commit](https://github.com/rnielikki/CustomMusicCreator/commit/b303e1e3fd4fed16347b831fadc943d870311580).
